/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torch/cuda/__init__.py:82: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0
2022-07-28 11:08:01,445 INFO     ---------------------------------------------------------------------------------------------
2022-07-28 11:08:01,445 INFO     Geo: cqd
2022-07-28 11:08:01,445 INFO     Data Path: data/FB15k-237-betae
2022-07-28 11:08:01,445 INFO     #entity: 14505
2022-07-28 11:08:01,445 INFO     #relation: 474
2022-07-28 11:08:01,445 INFO     #max steps: 150000
2022-07-28 11:08:01,445 INFO     Evaluate unoins using: DNF
2022-07-28 11:08:01,445 INFO     loading data
2022-07-28 11:08:43,139 INFO     Training info:
2022-07-28 11:08:43,143 INFO     Validation info:
2022-07-28 11:08:43,146 INFO     ip: 5000
2022-07-28 11:08:43,149 INFO     Test info:
2022-07-28 11:08:43,149 INFO     ip: 5000
posix.uname_result(sysname='Linux', nodename='gonzo-605-17.local', release='3.10.0-1160.49.1.el7.x86_64', version='#1 SMP Tue Nov 30 15:51:32 UTC 2021', machine='x86_64')
Traceback (most recent call last):
  File "main.py", line 632, in <module>
    main(parse_args())
  File "main.py", line 425, in main
    model = CQD(nentity,
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 191, in __init__
    self.batch_entity_range = self.batch_entity_range.cuda()
  File "/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA driver initialization failed, you might not have a CUDA gpu.
