2022-07-15 09:34:39,601 INFO     ---------------------------------------------------------------------------------------------
2022-07-15 09:34:39,601 INFO     Geo: cqd
2022-07-15 09:34:39,601 INFO     Data Path: data/FB15k-237-betae
2022-07-15 09:34:39,601 INFO     #entity: 14505
2022-07-15 09:34:39,601 INFO     #relation: 474
2022-07-15 09:34:39,602 INFO     #max steps: 150000
2022-07-15 09:34:39,602 INFO     Evaluate unoins using: DNF
2022-07-15 09:34:39,602 INFO     loading data
2022-07-15 09:35:13,735 INFO     Training info:
2022-07-15 09:35:13,738 INFO     2i: 149689
2022-07-15 09:35:14,384 INFO     Validation info:
2022-07-15 09:35:14,384 INFO     2i: 5000
2022-07-15 09:35:14,386 INFO     Test info:
2022-07-15 09:35:14,386 INFO     2i: 5000
2022-07-15 09:35:17,710 INFO     Model Parameter Configuration:
2022-07-15 09:35:17,711 INFO     Parameter embeddings.0.weight: torch.Size([14505, 2000]), require_grad = False
2022-07-15 09:35:17,711 INFO     Parameter embeddings.1.weight: torch.Size([474, 2000]), require_grad = False
2022-07-15 09:35:17,711 INFO     Parameter score_transform_fun.weight: torch.Size([2, 2000]), require_grad = True
2022-07-15 09:35:17,711 INFO     Parameter score_transform_fun.bias: torch.Size([2]), require_grad = True
2022-07-15 09:35:17,711 INFO     Parameter Number: 4002
2022-07-15 09:35:17,800 INFO     Loading checkpoint models/fb15k-237-betae...
2022-07-15 09:35:18,050 INFO     tasks = 2i
2022-07-15 09:35:18,050 INFO     init_step = 99999
2022-07-15 09:35:18,051 INFO     Start Training...
2022-07-15 09:35:18,051 INFO     learning_rate = 0
2022-07-15 09:35:18,051 INFO     batch_size = 1024
2022-07-15 09:35:18,051 INFO     hidden_dim = 1000
2022-07-15 09:35:18,051 INFO     gamma = 12.000000
/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in DivBackward0. Traceback of forward call that caused the error:
  File "main.py", line 632, in <module>
    main(parse_args())
  File "main.py", line 543, in main
    log = KGReasoning.train_step(model, optimizer, train_other_iterator, args, step)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/models.py", line 674, in train_step
    model.forward(positive_sample=positive_sample,
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 451, in forward
    scores = d2.query_2i(entity_embeddings=self.embeddings[0],
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/discrete.py", line 182, in query_2i
    res = t_norm(scores_1, scores_2)
  File "/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torchnorms/tnorms/classic.py", line 63, in __call__
    return (a * b) / (1.0 + (1.0 - a) * (1.0 - b))
 (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
posix.uname_result(sysname='Linux', nodename='gonzo-605-14.local', release='3.10.0-1160.49.1.el7.x86_64', version='#1 SMP Tue Nov 30 15:51:32 UTC 2021', machine='x86_64')
Traceback (most recent call last):
  File "main.py", line 632, in <module>
    main(parse_args())
  File "main.py", line 543, in main
    log = KGReasoning.train_step(model, optimizer, train_other_iterator, args, step)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/models.py", line 931, in train_step
    loss.backward()
  File "/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'DivBackward0' returned nan values in its 0th output.
